### ISSUE TITLE
体验了一下。创建表格报错

### ISSUE THREAD

**Issue by flyRen** [webman-php/admin#1]
### windows
```
PS D:\code\toys\webman-admin> php -v
PHP 7.4.15 (cli) (built: Feb  2 2021 20:47:36) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```
```
{
    "code": 500,
    "message": "Call to undefined method Illuminate\\Database\\MySqlConnection::schema()",
    "type": "failed",
    "traces": "Error: Call to undefined method Illuminate\\Database\\MySqlConnection::schema() in D:\\code\\toys\\webman-admin\\plugin\\admin\\app\\controller\\database\\TableController.php:87\nStack trace:\n#0 D:\\code\\toys\\webman-admin\\vendor\\workerman\\webman-framework\\src\\App.php(276): plugin\\admin\\app\\controller\\database\\TableController->create(Object(support\\Request))\n#1 D:\\code\\toys\\webman-admin\\plugin\\admin\\app\\middleware\\AccessControl.php(21): Webman\\App::Webman\\{closure}(Object(support\\Request))\n#2 D:\\code\\toys\\webman-admin\\vendor\\workerman\\webman-framework\\src\\App.php(271): plugin\\admin\\app\\middleware\\AccessControl->process(Object(support\\Request), Object(Closure))\n#3 D:\\code\\toys\\webman-admin\\vendor\\workerman\\webman-framework\\src\\App.php(118): Webman\\App::Webman\\{closure}(Object(support\\Request))\n#4 D:\\code\\toys\\webman-admin\\vendor\\workerman\\workerman\\Connection\\TcpConnection.php(638): Webman\\App->onMessage(Object(Workerman\\Connection\\TcpConnection), Object(support\\Request))\n#5 D:\\code\\toys\\webman-admin\\vendor\\workerman\\workerman\\Events\\Select.php(295): Workerman\\Connection\\TcpConnection->baseRead(Resource id #296)\n#6 D:\\code\\toys\\webman-admin\\vendor\\workerman\\workerman\\Worker.php(2465): Workerman\\Events\\Select->loop()\n#7 D:\\code\\toys\\webman-admin\\vendor\\workerman\\workerman\\Worker.php(1449): Workerman\\Worker->run()\n#8 D:\\code\\toys\\webman-admin\\vendor\\workerman\\workerman\\Worker.php(1392): Workerman\\Worker::forkWorkersForWindows()\n#9 D:\\code\\toys\\webman-admin\\vendor\\workerman\\workerman\\Worker.php(557): Workerman\\Worker::forkWorkers()\n#10 D:\\code\\toys\\webman-admin\\vendor\\workerman\\webman-framework\\src\\support\\App.php(124): Workerman\\Worker::runAll()\n#11 D:\\code\\toys\\webman-admin\\start.php(4): support\\App::run()\n#12 {main}"
}
```
### composer 文件
```
{
  "name": "workerman/webman",
  "type": "project",
  "keywords": [
    "high performance",
    "http service"
  ],
  "homepage": "http://www.workerman.net",
  "license": "MIT",
  "description": "High performance HTTP Service Framework.",
  "authors": [
    {
      "name": "walkor",
      "email": "walkor@workerman.net",
      "homepage": "http://www.workerman.net",
      "role": "Developer"
    }
  ],
  "support": {
    "email": "walkor@workerman.net",
    "issues": "https://github.com/walkor/webman/issues",
    "forum": "http://wenda.workerman.net/",
    "wiki": "http://workerman.net/doc/webman",
    "source": "https://github.com/walkor/webman"
  },
  "require": {
    "php": ">=7.2",
    "workerman/webman-framework": "^1.4.3",
    "monolog/monolog": "^2.0",
    "webman/admin": "^0.2.4"
  },
  "suggest": {
    "ext-event": "For better performance. "
  },
  "autoload": {
    "psr-4": {
      "": "./",
      "App\\": "./app"
    },
    "files": [
      "./support/helpers.php"
    ]
  },
  "scripts": {
    "post-package-install": [
      "support\\Plugin::install"
    ],
    "post-package-update": [
      "support\\Plugin::install"
    ],
    "pre-package-uninstall": [
      "support\\Plugin::uninstall"
    ]
  }
}

```

**Comment by walkor** [comment]
composer 安装webman/admin 时里会自动给安装依赖 lluminate/database，不清楚为什么你的没有安装？webman/admin 源码直接拷贝过来的？

**Comment by walkor** [comment]
https://www.workerman.net/plugin/82

**Comment by flyRen** [comment]
> composer 安装webman/admin 时里会自动给安装依赖 lluminate/database，不清楚为什么你的没有安装？webman/admin 源码直接拷贝过来的？

就看弄了一个webman-admin。  就执行了
```
composer create-project workerman/webman
composer require -W webman/admin
```
有自动安装依赖。但是为什么没有出现在composer.json里面就不清楚了
安装完成后 lluminate/database vendor下面这些代码都是有的。其他几个页面能正常， 比如数据库的列表，但是创建字段的时候就报错。 比如的以下列表都能正常访问
 - 账号管理
 - 角色管理
 - 菜单管理
 - 数据库->所有表
 - 用户管理 -> 用户

**Comment by walkor** [comment]
先卸载，然后升级到 0.2.5

**Comment by theonewu** [comment]
boss啥时候更新啊！

**Comment by walkor** [comment]
这几天
