### ISSUE TITLE
安装step2报错

### ISSUE THREAD

**Issue by lincome** [webman-php/admin#23]
![image](https://user-images.githubusercontent.com/7379732/223316127-7bd7ff89-9c32-4e60-b968-d9a6a4f3aba2.png)
```
{
    "code": 500,
    "msg": "Call to a member function connection() on null",
    "type": "failed",
    "traces": "Error: Call to a member function connection() on null in E:\\test\\webman\\vendor\\illuminate\\database\\Eloquent\\Model.php:1344\nStack trace:\n#0 E:\\test\\webman\\vendor\\illuminate\\database\\Eloquent\\Model.php(1310): Illuminate\\Database\\Eloquent\\Model::resolveConnection('plugin.admin.my...')\n#1 E:\\test\\webman\\vendor\\illuminate\\database\\Eloquent\\Model.php(1116): Illuminate\\Database\\Eloquent\\Model->getConnection()\n#2 E:\\test\\webman\\vendor\\illuminate\\database\\Eloquent\\Model.php(1033): Illuminate\\Database\\Eloquent\\Model->newBaseQueryBuilder()\n#3 E:\\test\\webman\\vendor\\illuminate\\database\\Eloquent\\Model.php(1069): Illuminate\\Database\\Eloquent\\Model->newModelQuery()\n#4 E:\\test\\webman\\vendor\\illuminate\\database\\Eloquent\\Model.php(1022): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()\n#5 E:\\test\\webman\\vendor\\illuminate\\database\\Eloquent\\Model.php(1736): Illuminate\\Database\\Eloquent\\Model->newQuery()\n#6 E:\\test\\webman\\vendor\\illuminate\\database\\Eloquent\\Model.php(1748): Illuminate\\Database\\Eloquent\\Model->__call('first', Array)\n#7 E:\\test\\webman\\plugin\\admin\\app\\controller\\InstallController.php(201): Illuminate\\Database\\Eloquent\\Model::__callStatic('first', Array)\n#8 E:\\test\\webman\\vendor\\workerman\\webman-framework\\src\\App.php(319): plugin\\admin\\app\\controller\\InstallController->step2(Object(support\\Request))\n#9 E:\\test\\webman\\vendor\\workerman\\webman-framework\\src\\App.php(349): Webman\\App::Webman\\{closure}(Object(support\\Request))\n#10 E:\\test\\webman\\plugin\\admin\\app\\middleware\\AccessControl.php(47): Webman\\App::Webman\\{closure}(Object(support\\Request))\n#11 E:\\test\\webman\\vendor\\workerman\\webman-framework\\src\\App.php(341): plugin\\admin\\app\\middleware\\AccessControl->process(Object(support\\Request), Object(Closure))\n#12 E:\\test\\webman\\vendor\\workerman\\webman-framework\\src\\App.php(141): Webman\\App::Webman\\{closure}(Object(support\\Request))\n#13 E:\\test\\webman\\vendor\\workerman\\workerman\\Connection\\TcpConnection.php(646): Webman\\App->onMessage(Object(Workerman\\Connection\\TcpConnection), Object(support\\Request))\n#14 E:\\test\\webman\\vendor\\workerman\\workerman\\Events\\Select.php(311): Workerman\\Connection\\TcpConnection->baseRead(Resource id #199)\n#15 E:\\test\\webman\\vendor\\workerman\\workerman\\Worker.php(1479): Workerman\\Events\\Select->loop()\n#16 E:\\test\\webman\\vendor\\workerman\\workerman\\Worker.php(1399): Workerman\\Worker::forkWorkersForWindows()\n#17 E:\\test\\webman\\vendor\\workerman\\workerman\\Worker.php(560): Workerman\\Worker::forkWorkers()\n#18 E:\\test\\webman\\vendor\\workerman\\webman-framework\\src\\support\\App.php(131): Workerman\\Worker::runAll()\n#19 E:\\test\\webman\\start.php(4): support\\App::run()\n#20 {main}"
}
```

**Comment by walkor** [comment]
windows下用命令 `php windows.php` 自动webman

**Comment by walkor** [comment]
windows下用命令 `php windows.php` 自动webman

**Comment by lincome** [comment]
Thanks♪(･ω･)ﾉ
